### ISSUE TITLE
Haskell and NixOS

### ISSUE THREAD

**Issue by jagajaga** [puffnfresh/idrispkgs#1]
Nice work! But please note, that in some time `cabal.mkDerivation` is going to be deprecated in `NixOS`, because there is a new generation of haskell pkgs managing called `haskellng`.

**Comment by puffnfresh** [comment]
@jagajaga I'm very aware of haskellng! :+1:

I'll port the Idris derivation over.

**Comment by jagajaga** [comment]
Oh, that's nice! :)
